# Generated by Django 5.1.1 on 2024-10-02 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('mensagem', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField()),
                ('fim', models.DateTimeField()),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], max_length=50)),
                ('preco_a_pagar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('foto_do_contrato', models.ImageField(blank=True, null=True, upload_to='ImovelAluguel')),
            ],
        ),
        migrations.CreateModel(
            name='ImovelAluguel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_do_Imovel', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=200)),
                ('preco_por_mes', models.DecimalField(decimal_places=2, max_digits=10)),
                ('disponibilidade', models.BooleanField()),
                ('inicio', models.DateTimeField()),
                ('fim', models.DateTimeField()),
                ('foto_da_casa', models.ImageField(blank=True, null=True, upload_to='ImovelAluguel')),
            ],
        ),
    ]
