# Generated by Django 5.1.1 on 2024-09-15 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descriacao', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=60)),
                ('telefone', models.CharField(max_length=40)),
                ('endereco', models.CharField(max_length=150)),
                ('data_de_nascimento', models.DateField(max_length=10)),
                ('ativo', models.BooleanField()),
            ],
        ),
    ]
