# Generated by Django 5.1.1 on 2024-09-28 12:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='data_cadastro',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
