# Generated by Django 5.1.1 on 2024-09-28 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_produto_data_cadastro'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='foto_produto',
            field=models.ImageField(blank=True, null=True, upload_to='produtos'),
        ),
    ]
