# Generated by Django 5.1.1 on 2024-10-01 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=200)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estoque', models.IntegerField()),
                ('codigo', models.CharField(max_length=30)),
                ('disponibilidade', models.BooleanField()),
                ('data_cadastro', models.DateField()),
                ('foto_da_casa', models.ImageField(blank=True, null=True, upload_to='produtos')),
            ],
        ),
    ]
