# Generated by Django 5.1.1 on 2024-10-01 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vendas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venda',
            old_name='codigo',
            new_name='endereço',
        ),
    ]
