# Generated by Django 5.1.1 on 2024-10-01 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vendas', '0002_rename_codigo_venda_endereço'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='foto_da_casa',
            field=models.ImageField(blank=True, null=True, upload_to='Vendas'),
        ),
    ]
