# Generated by Django 5.1.1 on 2024-10-02 17:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vendas', '0004_reserva_rename_data_cadastro_venda_data_da_compra'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='data_da_reserva',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='descricao',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='disponibilidade',
            field=models.BooleanField(default='a definir'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='endereço',
            field=models.CharField(default='a definir', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='estoque',
            field=models.IntegerField(default='a definir'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='foto_da_casa',
            field=models.ImageField(blank=True, null=True, upload_to='Reserva'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='preco',
            field=models.DecimalField(decimal_places=2, default='a definir', max_digits=10),
            preserve_default=False,
        ),
    ]
