# Generated by Django 5.1.1 on 2024-10-02 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vendas', '0005_reserva_data_da_reserva_reserva_descricao_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='nome',
            new_name='nome_da_casa_a_ser_reservada',
        ),
    ]
