# Generated by Django 5.1.1 on 2024-10-02 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vendas', '0006_rename_nome_reserva_nome_da_casa_a_ser_reservada'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reserva',
        ),
    ]
